name: Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feat/**'
    paths:
      - .github/workflows/image.yml
      - docker/ubuntu/Dockerfile
  schedule:
    - cron: "0 3 * * 1"

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_FILE: docker/ubuntu/Dockerfile
      IMAGE_NAME: ${{ github.event.repository.name }}-ubuntu
      IMAGE_TAG: 24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.IMAGE_FILE }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache: ${{ github.event_name == 'schedule' }}
          build-args: |
            REFRESH_TS=${{ github.run_id }}
